from django.conf.urls import patterns, url
from des import views

urlpatterns = patterns('',
    url(r'des/list_attribute_types/$', views.list_attribute_types, name='list_attribute_types'),
    url(r'des/list_attribute_types/create_attribute_type/$', views.create_attribute_type, name='create_attribute_type'),
    url(r'des/list_attribute_types/modify_attribute_type/(?P<id_attribute_type>\d+)/$', views.modify_attribute_type, name='modify_attribute_type'),
    url(r'des/list_attribute_types/delete_attribute_type/(?P<id_attribute_type>\d+)/$', views.delete_attribute_type, name='delete_attribute_type'),
    url(r'des/list_attribute_types/visualize_attribute_type/(?P<id_attribute_type>\d+)/$', views.visualize_attribute_type, name='visualize_attribute_type'),
    url(r'des/list_attributes/$', views.list_attributes, name='list_attributes'),
    url(r'des/list_attributes/create_attribute/$', views.create_attribute, name='create_attribute'),
    url(r'des/list_attributes/modify_attribute/(?P<id_attribute>\d+)/$', views.modify_attribute, name='modify_attribute'),
    url(r'des/list_attributes/delete_attribute/(?P<id_attribute>\d+)/$', views.delete_attribute, name='delete_attribute'),
    url(r'des/list_attributes/visualize_attribute/(?P<id_attribute>\d+)/$', views.visualize_attribute, name='visualize_attribute'),
    url(r'des/list_attributes/assign_attribute_type/(?P<id_attribute>\d+)/$', views.assign_attribute_type, name='assign_attribute_type'),
    url(r'des/list_attributes/assign_attribute_type/(?P<id_attribute>\d+)/grant_attribute_type/(?P<id_attribute_type>\d+)$', views.grant_attribute_type, name='grant_attribute_type'),
    url(r'des/list_attributes/assign_attribute_value/(?P<id_attribute>\d+)/$', views.assign_attribute_value, name='assign_attribute_value'),
    url(r'des/list_item_types/$', views.list_item_types, name='list_item_types'),
    url(r'des/list_item_types/create_item_type/$', views.create_item_type, name='create_item_type'),
    url(r'des/list_item_types/modify_item_type/(?P<id_item_type>\d+)/$', views.modify_item_type, name='modify_item_type'),
    url(r'des/list_item_types/delete_item_type/(?P<id_item_type>\d+)/$', views.delete_item_type, name='delete_item_type'),
    url(r'des/list_item_types/visualize_item_type/(?P<id_item_type>\d+)/$', views.visualize_item_type, name='visualize_item_type'),
    url(r'des/list_item_types/assign_item_attribute/(?P<id_item_type>\d+)/$', views.assign_item_attribute, name='assign_item_attribute'),
    url(r'des/list_item_types/assign_item_attribute/(?P<id_item_type>\d+)/grant_attribute/(?P<id_attribute>\d+)/$', views.grant_attribute, name='grant_attribute'),
    url(r'des/list_item_types/assign_item_attribute/(?P<id_item_type>\d+)/deny_attribute/(?P<id_attribute>\d+)/$', views.deny_attribute, name='deny_attribute'),
    url(r'des/list_items/$', views.list_items, name='list_items'),
    url(r'des/list_items/create_item/$', views.create_item, name='create_item'),
    url(r'des/list_items/modify_item/(?P<id_item>\d+)/$', views.modify_item, name='modify_item'),
    url(r'des/list_items/delete_item/(?P<id_item>\d+)/$', views.delete_item, name='delete_item'),
    url(r'des/list_items/revert_item/')
)